### ISSUE TITLE
GLFW Throws platform unsupported on linux

### ISSUE THREAD

**Issue by byte-0x74** [dotnet/Silk.NET#1224]
# Summary
When i'm trying to create new window i get this Error:
System.PlatformNotSupportedException: GLFW is not supported on this platform.
   at Silk.NET.Windowing.Glfw.GlfwPlatform.ThrowUnsupported()
   at Silk.NET.Windowing.Glfw.GlfwPlatform.CreateWindow(WindowOptions options)
   at Silk.NET.Windowing.Window.Create(WindowOptions options)

i have called Registerplatform for GlfwWindowing and GlfwInput before creating new window

# Steps to reproduce
- Platform: Desktop - Fedora 37 Workstation (Wayland Windowing System)
- Framework Version: .NET 7.0
- API: OpenGL
- API Version: OpenGL 4.6
1.Call platform registers for GlfwWindow and GlfwInput
2.Create new window
3.Run Window

Not sure if  this is a bug or Silk.NET just simply don't support glfw windowing on linux with wayland windowing system.

**Comment by Beyley** [comment]
You need to install GLFW using your system package manager, which seems to be fedora, so you can use `yum`, and install glfw with `yum glfw`

**Comment by byte-0x74** [comment]
installed and still same issue
