### ISSUE TITLE
GL Context fails to be created on Raspberry Pi (arm64)

### ISSUE THREAD

**Issue by midwan** [dotnet/Silk.NET#1277]
# Summary
It seems that Silk.NET fails to open a GL context on a Raspberry Pi (running Manjaro Linux, aarch64), while it works on a Linux-x64 (also running Manjaro Linux). When the window is opened, the below error is thrown (the extract is from a specific project using Silk.NET):

```
Could not create GL context: GLXBadFBConfig
   at Silk.NET.SDL.Sdl.ThrowError()
   at Silk.NET.SDL.SdlContext.Create(ValueTuple`2[] attributes)
   at Silk.NET.Windowing.Sdl.SdlView.CoreInitialize(ViewOptions opts, Nullable`1 additionalFlags, Nullable`1 x, Nullable`1 y, Nullable`1 w, Nullable`1 h, String title, IGLContext sharedContext)
   at Silk.NET.Windowing.Sdl.SdlWindow.CoreInitialize(ViewOptions opts)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
Press return to exit
```

Reading about the error, it seems that based on the specification of [GLX_ARB_create_context](https://www.khronos.org/opengl/wiki/OpenGL_Context#Context_types), the GLXBadFBConfig error may be returned:

```
If <config> does not support compatible OpenGL contexts
    providing the requested API major and minor version,
    forward-compatible flag, and debug context flag, GLXBadFBConfig
    is generated.
```

So this might be a case of Silk.NET requesting a major/minor version that is not supported on these devices, but I'm not 100% sure yet.

The output of `glxinfo | grep -e "OpenGL version" -e "Core" -e "Compatible"` on the device is the following:
```
OpenGL version string: 2.1 Mesa 22.3.4
```

Is this the case, and if so, is it configurable?

**Comment by Perksey** [comment]
Please note that we do not officially support using SDL anywhere other than Android and iOS - you should assume that the backend is broken on desktop. Please use GLFW instead.

**Comment by midwan** [comment]
@Perksey 
I don't think there was any direct reference to SDL, but just to be sure, I changed the API used to OpenGL specifically, and requested version 2.1 in the parameters:
```
var api = new GraphicsAPI
                (ContextAPI.OpenGL, ContextProfile.Core, ContextFlags.Default, new APIVersion(2, 1));
```

However, on startup I still get an error about the OpenGL version not being supported:
```
OpenGL version 3.1 is required for rendering. Your version is 2.1.
   at Ambermoon.Renderer.Context..ctor(State state, Int32 width, Int32 height, Single aspect)
   at Ambermoon.Renderer.OpenGL.RenderView..ctor(IContextProvider contextProvider, IGameData gameData, IGraphicProvider graphicProvider, ITextProcessor textProcessor, Func`1 textureAtlasManagerProvider, Int32 framebufferWidth, Int32 framebufferHeight, Size windowSize, Boolean& useFrameBuffer, Boolean& useEffectFrameBuffer, Func`1 screenBufferModeProvider, Func`1 effectProvider, Graphic[] additionalPalettes, DeviceType deviceType, SizingPolicy sizingPolicy, OrientationPolicy orientationPolicy)
   at Ambermoon.GameWindow.CreateRenderView(GameData gameData, IConfiguration configuration, GraphicProvider graphicProvider, FontProvider fontProvider, Graphic[] additionalPalettes, Func`1 textureAtlasManagerProvider)
   at Ambermoon.GameWindow.ShowVersionSelector(BinaryReader builtinVersionReader, Action`4 selectHandler, TextureAtlasManager& createdTextureAtlasManager)
   at Ambermoon.GameWindow.Window_Load()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
```

It seems that 3.1 is hardcoded as the minimum required version?

**Comment by Perksey** [comment]
Makes sense, you'd have a hard time getting anything to run on anything below 3.x these days.

**Comment by Beyley** [comment]
Closing as this _seems_ like an issue downstream in Ambermoon, as its throwing the required GL version error, not us
Feel free to re-open if i missed something

**Comment by midwan** [comment]
We sort of made it work with using OpenGLES instead of OpenGL, so yeah, I think this can be closed for now.
