### ISSUE TITLE
Rendering NV12 exception with OpenGLES

### ISSUE THREAD

**Issue by qqJoker** [dotnet/Silk.NET#1388]
When I use OpenGLES to render video in NV12 format, an exception occurs when calling the TexImage2D method: 
``` C#
System.AccessViolationException: 
      "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
```

Here is my code：
``` C#
 public unsafe void Bind(FrameCacheModel frame, MyShader shader)
{
        for (int i = 0; i < this._handles.Length; i++)
        {
            this._gl.ActiveTexture((TextureUnit)(33984 + i));
            this._gl.BindTexture(TextureTarget.Texture2D, this._handles[i]);
            this._gl.PixelStore(PixelStoreParameter.UnpackRowLength, frame.LineSizeArr[(uint)i]);
            var width = i == 0 ? frame.Width : frame.Width / 2;
            var height = i == 0 ? frame.Height : frame.Height / 2;
this._gl.TexImage2D(TextureTarget.Texture2D,0,InternalFormat.Red,width,height,0,PixelFormat.Red,PixelType.UnsignedByte,frame.Data[(uint)i]);
           this._gl.Uniform1(shader.TexYuvUniform[i],i);
        }
}
```

**Comment by qqJoker** [comment]
Error :
``` C#
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
 at Silk.NET.OpenGLES.GL.TexImage2D(Silk.NET.OpenGLES.TextureTarget, Int32, Silk.NET.OpenGLES.InternalFormat, UInt32, UInt32, Int32, Silk.NET.OpenGLES.PixelFormat, Silk.NET.OpenGLES.PixelType, Void*)
 at AvaloniaPlayers.Controls.OpenGlPlayer.Tools.MyTexture.Bind(FFmpegPlayerSharp.Core.Models.FrameCacheModel, AvaloniaPlayers.Controls.OpenGlPlayer.Tools.MyShader)
 at AvaloniaPlayers.Controls.OpenGlPlayer.Player.OnOpenGlRender(Avalonia.OpenGL.GlInterface, Int32)
 at Avalonia.OpenGL.Controls.OpenGlControlBase.Update()
 at Avalonia.Rendering.Composition.Compositor.CommitCore()
 at Avalonia.Rendering.Composition.Compositor.Commit()
 at Avalonia.Rendering.Composition.Compositor.<.ctor>b__25_0()
 at Avalonia.Threading.JobRunner.RunJobs(System.Nullable`1<Avalonia.Threading.DispatcherPriority>)
 at Avalonia.Win32.Win32Platform.WndProc(IntPtr, UInt32, IntPtr, IntPtr)
 at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG ByRef)
 at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG ByRef)
 at Avalonia.Win32.Win32Platform.RunLoop(System.Threading.CancellationToken)
 at Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken)
 at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(System.String[])
 at Program.Main(System.String[])
```

**Comment by Beyley** [comment]
This feels like a bug upstream in Avalonia, i would open an issue there, if it is our bug, please re-open!

**Comment by qqJoker** [comment]
ths,I have raised an issue under Avalonia
