### ISSUE TITLE
System.MissingMethodException: Method not found: 'ImGuiNET.ImFontPtr ImGuiNET.ImFontAtlasPtr.AddFontFromFileTTF

### ISSUE THREAD

**Issue by ikpil** [dotnet/Silk.NET#1757]
# Summary
Please upgrade the following in the demo project:
- https://github.com/ikpil/DotRecast

Upgrade Silk.NET to version 2.18.0.
Upgrade Silk.NET.OpenGL.Extensions.ImGui to version 2.18.0.

Reproduces when running the demo.

# Steps to reproduce
- Platform: Desktop
- Framework Version: dotnet 7.0
- API: OpenGL
- API Version: Vulkan 1.2/OpenGL 4.3 Legacy/OpenGL 4.5 Core/OpenGLES 3.2
1. First I did this
```
       ImGuiFontConfig imGuiFontConfig = new(Path.Combine("resources\\fonts", "DroidSans.ttf"), 16, null);
        _imgui = new ImGuiController(_gl, window, _input, imGuiFontConfig);
```
2. Then I did this
System.MissingMethodException: Method not found: 'ImGuiNET.ImFontPtr ImGuiNET.ImFontAtlasPtr.AddFontFromFileTTF(System.String, Single, ImGuiNET.ImFontConfigPtr, IntPtr)'.
   at Silk.NET.OpenGL.Extensions.ImGui.ImGuiController..ctor(GL gl, IView view, IInputContext input, Nullable`1 imGuiFontConfig, Action onConfigureIO)
   at Silk.NET.OpenGL.Extensions.ImGui.ImGuiController..ctor(GL gl, IView view, IInputContext input, ImGuiFontConfig imGuiFontConfig)
   at DotRecast.Recast.Demo.RecastDemo.OnWindowOnLoad() in D:\workspace\DotRecast\src\DotRecast.Recast.Demo\RecastDemo.cs:line 370
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at DotRecast.Recast.Demo.RecastDemo.Run() in D:\workspace\DotRecast\src\DotRecast.Recast.Demo\RecastDemo.cs:line 129
   at DotRecast.Recast.Demo.Program.StartDemo() in D:\workspace\DotRecast\src\DotRecast.Recast.Demo\Program.cs:line 52
   at DotRecast.Recast.Demo.Program.Main(String[] args) in D:\workspace\DotRecast\src\DotRecast.Recast.Demo\Program.cs:line 15

# Comments
...

**Comment by Perksey** [comment]
We're aware of the issue. Please note that Silk.NET don't actually provide the bindings, and as such this is their bug to fix: ImGuiNET/ImGui.NET#426.
