### ISSUE TITLE
ImGui extension for silk.net doesn't work.

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/Silk.NET#1785]
# Summary

ImGui is not working for silk.net

```
Exception has occurred: CLR/System.MissingMethodException
An unhandled exception of type 'System.MissingMethodException' occurred in Silk.NET.OpenGL.Extensions.ImGui.dll: 'Method not found: 'ImGuiNET.RangePtrAccessor`1<ImGuiNET.ImDrawListPtr> ImGuiNET.ImDrawDataPtr.get_CmdListsRange()'.'
   at Silk.NET.OpenGL.Extensions.ImGui.ImGuiController.RenderImDrawData(ImDrawDataPtr drawDataPtr)
   at Silk.NET.OpenGL.Extensions.ImGui.ImGuiController.Render()
   at Pure.Window.<>c__DisplayClass36_0.<Run>b__3(Double dt) in /home/shadowblitz16/Documents/source/cs/Pure/Pure/Source/Common/Windowing/Window.cs:line 102
   at Silk.NET.Windowing.Internals.ViewImplementationBase.DoRender()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Pure.Window.Run() in /home/shadowblitz16/Documents/source/cs/Pure/Pure/Source/Common/Windowing/Window.cs:line 135
   at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/source/cs/Pure/Pure.Editor/Program.cs:line 4
```

```cs
using Silk.NET.Input;
using Silk.NET.OpenGL;
using Silk.NET.OpenGL.Extensions.ImGui;
using Silk.NET.Windowing;

namespace Pure;
public abstract class Window : IDisposable
{
    GL?              _gl = null;
    IInputContext?   _input;
    private float    _delta;
    private IWindow? _window;
    private bool    _wasLoaded;
    private bool    _wasMoved;
    private bool    _wasResized;
    private bool    _wasDisposed;
    private ImGuiController? _imGuiController;

    public string Title  { get; set; } = "Window";
    public int    X      { get; set; } = -1;
    public int    Y      { get; set; } = -1;
    public uint   Width  { get; set; } = 160*4;
    public uint   Height { get; set; } = 144*4;

    public Window()
    {

    }
    public Window(string title)
    {
        Title = title;
    }
    public Window(uint width, uint height)
    {
        Width  = width;
        Height = height;
    }
    public Window(int x, int y, uint width, uint height) : this(width, height)
    {
        X = x;
        Y = y;
    }
    public Window(string title, uint width, uint height) : this(width, height)
    {
        Title = title;
    }
    public Window(string title, int x, int y, uint width, uint height) : this(x, y, width, height)
    {
        Title = title;
    }
    
    ~Window()
    {
        Dispose();
    }
    public void Run    ()
    {
        var x      = X;
        var y      = Y;
        var width  = Width;
        var height = Height;
        var title  = Title;
        _window = Silk.NET.Windowing.Window.Create(WindowOptions.Default with
        {
            Title    = Title,
            Position = new((int)X    , (int)Y     ),
            Size     = new((int)Width, (int)Height),
            UpdatesPerSecond = 60,
        });
        _window.Load += () =>
        {
            _gl              = _window.CreateOpenGL();
            _input           = _window.CreateInput();
            _imGuiController = new ImGuiController(_gl, _window, _input);
        };
        _window.Move += (v) =>
        {
            X = v.X;
            Y = v.Y;
            _wasMoved = true;
        };
        _window.Resize += (v) =>
        {
            Width = (uint)v.X;
            Height = (uint)v.Y;
            _wasResized = true;
        };
        _window.Render += (dt) =>
        {
            _delta = (float)dt;
            if (!_wasLoaded) 
            {
                OnLoad();
            }
            _imGuiController?.Update(_delta);


            _gl?.ClearColor(0,0,0,0);
            _gl?.Clear((uint)ClearBufferMask.ColorBufferBit);
            
            OnUpdate();
            _imGuiController?.Render();

            if (X     != x     || Y      != y     )
            {
                x = X;
                y = Y;
                _window.Position = new(x,y);
            }
            if (Width != width || Height != height)
            {
                width  = Width;
                height = Height;
                _window.Size = new((int)width,(int)Height);
            }
            if (Title != title)
            {
                title = Title;
                _window.Title = title;
            }
            
            _wasLoaded  = true;
            _wasMoved   = false;
            _wasResized = false;
        };
        _window.Closing += () =>
        {
            OnUnload();
            _imGuiController?.Dispose();
        };
        _window.FramebufferResize += s =>
        {
            _gl?.Viewport(s);
        };
        _window.Run();
    }
    public void Dispose()
    {
        if (_wasDisposed) return;
        _wasDisposed = true;
        _imGuiController?.Dispose();
        _window?.Dispose();
        GC.SuppressFinalize(this);
    }

    public bool  WasLoaded () => _wasLoaded;
    public bool  WasMoved  () => _wasMoved;
    public bool  WasResized() => _wasResized;

    protected virtual void OnLoad  ()
    {

    }
    protected virtual void OnUnload()
    {

    }
    protected virtual void OnUpdate()
    {

    }
}

using Pure;
using ImGuiNET;
public sealed class Editor : Window
{

    public Editor() : base("Pure Editor")
    {

    }

    protected override void OnLoad  ()
    {
        base.OnLoad();
        ImGui.GetIO().ConfigFlags |= ImGuiConfigFlags.DockingEnable | ImGuiConfigFlags.ViewportsEnable;
    }
    protected override void OnUpdate()
    {
        base.OnUpdate();

        if (ImGui.BeginMainMenuBar())
        {
            if (ImGui.BeginMenu("Tools"))
            {
                if (ImGui.MenuItem("Screen")) Screen.Toggle();
                ImGui.EndMenu();
            }
            ImGui.EndMainMenuBar();
        }

        ImGui.DockSpaceOverViewport();
    }
}

using Pure;
using ImGuiNET;
public static class Screen 
{
    public static bool Enabled { get; set; }

    public static void Show  ()
    {
        Enabled = true;
    }
    public static void Hide  ()
    {
        Enabled = false;
    }
    public static void Toggle()
    {
        Enabled = !Enabled;
    }

    public static void Render()
    {
        if (Enabled && ImGui.Begin("Screen"))
        {
            ImGui.End();
        }
    }
}
```
# Steps to reproduce
- Platform: Kubuntu 22.04 Desktop
- Framework Version: .NET 7.0
- API: OpenGL
- API Version: What ever silk.net 2.18.0 uses by default.
See code above...

# Comments
I was getting another error with 1.89.9.1 version but I updated to 1.89.9.3...
```
Exception has occurred: CLR/System.MissingMethodException
An unhandled exception of type 'System.MissingMethodException' occurred in Silk.NET.OpenGL.Extensions.ImGui.dll: 'Method not found: 'ImGuiNET.ImFontPtr ImGuiNET.ImFontAtlasPtr.AddFontFromFileTTF(System.String, Single, ImGuiNET.ImFontConfigPtr, IntPtr)'.'
   at Silk.NET.OpenGL.Extensions.ImGui.ImGuiController..ctor(GL gl, IView view, IInputContext input, Nullable`1 imGuiFontConfig, Action onConfigureIO)
   at Silk.NET.OpenGL.Extensions.ImGui.ImGuiController..ctor(GL gl, IView view, IInputContext input)
   at Pure.Window.<>c__DisplayClass34_0.<Run>b__2(Double dt) in /home/shadowblitz16/Documents/source/cs/Pure/Pure/Source/Common/Windowing/Window.cs:line 85
   at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Pure.Window.Run() in /home/shadowblitz16/Documents/source/cs/Pure/Pure/Source/Common/Windowing/Window.cs:line 119
   at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/source/cs/Pure/Pure.Editor/Program.cs:line 4
```

**Comment by Beyley** [comment]
There was a breaking change to ImGui.NET recently (already fixed seemingly), you'll have to use our experimental NuGet feed, or copy [this code](https://github.com/dotnet/Silk.NET/tree/feature/2.19.0/src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui) to your own project

**Comment by Shadowblitz16** [comment]
@Beyley what is the experimental NuGet feed?

**Comment by Perksey** [comment]
https://dotnet.github.io/Silk.NET/docs/silk.net/experimental-feed.html
