### ISSUE TITLE
Issue with Silk.NET texture processing

### ISSUE THREAD

**Issue by gotham-knight1** [dotnet/Silk.NET#2243]
I have a code which throws this message whenever I run the program and the Window immediately closes: 
```

Unhandled exception. Silk.NET.Core.Loader.SymbolLoadingException: Native symbol not found (Symbol: glTextureParameteri)
   at Silk.NET.GLFW.GlfwContext.<GetProcAddress>g__Throw|3_0(String proc)
   at Silk.NET.GLFW.GlfwContext.GetProcAddress(String proc, Nullable`1 slot)
   at Silk.NET.OpenGL.GL._B.get__DNG()
   at Silk.NET.OpenGL.GL.TextureParameter(UInt32 texture, GLEnum pname, Int32 param)
   at Blood.RenderTests.Tests.Load() in C:\Users\Enis Dacik\Desktop\Blood-master\Blood\RenderTests\Tests.cs:line 164
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Blood.RenderTests.Tests..ctor() in C:\Users\Enis Dacik\Desktop\Blood-master\Blood\RenderTests\Tests.cs:line 42
   at Blood.Program.Main(String[] args) in C:\Users\Enis Dacik\Desktop\Blood-master\Blood\Program.cs:line 13 
```
- Platform: Desktop
- Framework Version: .NET 4.8
- API: Vulkan/OpenGL
- API Version: Vulkan 1.2/OpenGL 4.3 Legacy/OpenGL 4.5 Core/OpenGLES 3.2
1. Attempt one to fix it was to change IDEs, but that didn't work;
2. Attempt two was to download a newer version of .NET framework;
3. Attempt three was to check if the code worked at all by compiling it on another PC, and it worked.

My guess it's the Silk.NET version but I have the latest one. I really don't know what the problem is.

**Comment by Perksey** [comment]
Have you checked using glGet* that the OpenGL version is 4.5 or higher? This function isn’t available on GLES. You’ll likely have to switch to using glTexParam*.

**Comment by gotham-knight1** [comment]
Yeah turns out I have 4.3. Nevermind, thanks for the help.
