### ISSUE TITLE
GlfwException: Invalid window hint

### ISSUE THREAD

**Issue by costructuralist** [dotnet/Silk.NET#547]
# Summary
The following error occurs when running the `Tutorial 1.1 - Hello Window` example project:

```
GLFW initialized
Unhandled exception. Silk.NET.GLFW.GlfwException: InvalidEnum: Invalid window hint 131082
   at Silk.NET.GLFW.Glfw.<>c.<.cctor>b__141_0(ErrorCode errorCode, String description) in E:\Source\random\Silk.NET-main\src\Windowing\Silk.NET.GLFW\Glfw.cs:line 50
   at Silk.NET.GLFW.Glfw.WindowHint(WindowHintBool hint, Boolean value) in E:\Source\random\Silk.NET-main\src\Windowing\Silk.NET.GLFW\Silk.NET.SilkTouch\Silk.NET.SilkTouch.NativeApiGenerator\Glfw.e243aba7-bc3d-4efb-97b5-3248c2f77979.gen.cs:line 3448
   at Silk.NET.Windowing.Glfw.GlfwWindow.CoreInitialize(WindowOptions opts) in E:\Source\random\Silk.NET-main\src\Windowing\Silk.NET.Windowing.Glfw\GlfwWindow.cs:line 335
   at Silk.NET.Windowing.Internals.WindowImplementationBase.CoreInitialize(ViewOptions opts) in E:\Source\random\Silk.NET-main\src\Windowing\Silk.NET.Windowing.Common\Internals\WindowImplementationBase.cs:line 69
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize() in E:\Source\random\Silk.NET-main\src\Windowing\Silk.NET.Windowing.Common\Internals\ViewImplementationBase.cs:line 95
   at Silk.NET.Windowing.WindowExtensions.Run(IView view) in E:\Source\random\Silk.NET-main\src\Windowing\Silk.NET.Windowing.Common\WindowExtensions.cs:line 45
   at Tutorial.Program.Main(String[] args) in E:\Source\random\Silk.NET-main\examples\CSharp\OpenGL Tutorials\Tutorial 1.1 - Hello Window\Program.cs:line 27
```

# Steps to reproduce
- Platform: Desktop (Windows 10)
- Framework Version: .NET Core 3.1
- API: OpenGL
- Silk.NET 2.6.0
1. dotnet build
2. dotnet run

**Comment by Perksey** [comment]
Can you verify what version of GLFW you have on your system? You can do this by putting the following code at the start of your program:
```cs
Console.WriteLine(GlfwProvider.GLFW.Value.GetVersionString());
```

**Comment by Perksey** [comment]
More information required but not given, closing...
