### ISSUE TITLE
Window with non-ASCII title throws on Run() in Silk.NET 2.11.0

### ISSUE THREAD

**Issue by EnoughTea** [dotnet/Silk.NET#736]
# Summary
Calling `Run()` on an OpenGL window with non-ASCII characters in its title throws a System.ArgumentException.
ASCII characters work fine.

# Steps to reproduce
- Platform: Desktop
- Framework Version: .NET 6
- API: OpenGL
- API Version: Core 3.3
- Silk.NET Version 2.11.0

Creating a window with Latin Small Letter Beta (U+A7B5) in its title...
```
var window = Silk.NET.Windowing.Window.Create(new WindowOptions
{
    Title = "ꞵ",
});
window.Run();
```
...results in:
```
System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'. (Parameter 'bytes')
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount)
   at Silk.NET.Core.Native.SilkMarshal.StringIntoSpan(String input, Span`1 span, NativeStringEncoding encoding)
   at Silk.NET.Core.Native.SilkMarshal.StringToMemory(String input, NativeStringEncoding encoding)
   at Silk.NET.Core.Native.SilkMarshal.StringToPtr(String input, NativeStringEncoding encoding)
   at Silk.NET.GLFW.Glfw.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, WindowHandle* share)
   at Silk.NET.Windowing.Glfw.GlfwWindow.CoreInitialize(WindowOptions opts)
   at Silk.NET.Windowing.Internals.WindowImplementationBase.CoreInitialize(ViewOptions opts)
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
```

**Comment by HurricanKai** [comment]
Is this character represented as 2+ bytes in UTF8?
We use some very basic sizing logic in this code path, so that's likely the issue.

**Comment by EnoughTea** [comment]
Yep, it takes 3 bytes in UTF8.

**Comment by HurricanKai** [comment]
I know an easy fix on net5 and above (using the "new" UTF8 class) but no idea on lower then that, I don't know a good efficient way of getting the size of the chars in.

**Comment by hyazinthh** [comment]
With 2.12.0 it does not crash anymore, but I get the following result for a title containing µ:

![Untitled](https://user-images.githubusercontent.com/39337420/150147545-0c279579-c3b3-40ce-84d6-c3a629a83938.png)

System is Windows 10.

**Comment by roeyskoe** [comment]
On my Win10 machine this does work.
<img width="106" alt="Screenshot_130" src="https://user-images.githubusercontent.com/26493216/150160110-e96d59e1-9425-4024-b98b-7b8f63e28513.png">
string: `ꞵµöä™قط😎`
