### ISSUE TITLE
How to set Android fullscreen and landscape？

### ISSUE THREAD

**Issue by CeSun** [dotnet/Silk.NET#863]
I try set RequestedOrientation on function OnResume, but that's an exception: 
```
System.InvalidOperationException
  Message=Only one SilkActivity may be present throughout the whole application.
```
![image](https://user-images.githubusercontent.com/54771283/160096315-ca6b414d-d77e-42ad-8802-c1f87ef4ab22.png)

**Comment by Perksey** [comment]
We don't have enough information in this issue to do anything here.

The issue isn't [likely] related to you setting the orientation, but without a stack trace I have no way to confirm that.

**Comment by CeSun** [comment]
> We don't have enough information in this issue to do anything here.
> 
> The issue isn't [likely] related to you setting the orientation, but without a stack trace I have no way to confirm that.

Sorry, I'm a little incoherent.
May I ask how to set the screen direction. I tried to do this as shown in the figure but it threw an exception.

**Comment by Perksey** [comment]
That is the correct way. I need to know more about the exception so I can help you.

**Comment by CeSun** [comment]
My Code:
```CSharp
using LiteEngine;
using Silk.NET.Windowing;
using Silk.NET.Windowing.Sdl.Android;
using Silk.NET.OpenGL;
using Android.OS;
namespace AndroidLauncher;

[Activity(Label = "@string/app_name", MainLauncher = true)]
public class MainActivity : SilkActivity
{
    private IView? view;
    private GL? Gl;
    protected override void OnResume()
    {
        Title = "LiteEngine - Android";
        base.OnResume();
        RequestedOrientation = Android.Content.PM.ScreenOrientation.Landscape;
    }
    protected override void OnRun()
    {
        var options = ViewOptions.Default;
        options.API = new GraphicsAPI(ContextAPI.OpenGLES, ContextProfile.Core, ContextFlags.Default, new APIVersion(3, 0));
        options.ShouldSwapAutomatically = true;
        options.FramesPerSecond = 120;
        options.UpdatesPerSecond = 60;
         view = Silk.NET.Windowing.Window.GetView(options);
        view.Load += Init;
        view.Update += Update;
        view.Render += Render;
        view.Run();
        Fini();
    }
    private void Update(double time) => Engine.Instance.Update((float)time);
    private void Render(double time) => Engine.Instance.Render();
    private void Init() => Engine.Instance.Init(Gl = GL.GetApi(view));
    private void Fini() => Engine.Instance.Fini();
}

```

Debug this code on my mobile, it will throw exception: 
```CSharp
System.InvalidOperationException: 'Only one SilkActivity may be present throughout the whole application.'
```
But the debugger doesn't break in my code, [External Code] is displayed in the call stack.

**Comment by CeSun** [comment]
IDE:
![image](https://user-images.githubusercontent.com/54771283/160138845-13bf727f-b4f0-4ff8-8b90-0b058f2b7c96.png)
Moblie:
![Screenshot_2022-03-25-22-21-10-61_038b6f90ec12b4a9714a1ac07fe4c75e](https://user-images.githubusercontent.com/54771283/160138938-482177d8-cc3a-4c2a-8067-4882361ddc04.jpg)

**Comment by Perksey** [comment]
You might need to disable "Just My Code" in Visual Studio, as well as enable "Native debugging".

You can do the former in Debug > Options, and the latter in Debug > [Project Name] Debug Properties.

Once you've done all that, hopefully you'll have a stack trace. And in any case, the output available in the "Output" window would be helpful as well.

**Comment by CeSun** [comment]
I've set up the first one, but I haven't found the second one, is this set to C++?

![image](https://user-images.githubusercontent.com/54771283/160140171-541f785e-232e-43af-968a-87e3672430e1.png)

**Comment by CeSun** [comment]
![image](https://user-images.githubusercontent.com/54771283/160140655-bdbd3f92-023a-4ab7-acb1-35164357c6e4.png)

**Comment by Perksey** [comment]
Hmmm, unfortunately doesn't give a lot more information - frustrating android.

Last thing: can you press "Continue" and let the application crash, and then attach the output of the "Output" window.

If after all that I'm not able to get any more information then I think I'm going to _attempt_ to put a bugfix in, but I'm going in blind so it might not work.

**Comment by CeSun** [comment]
Full Output:
```
Forwarding debugger port 8806
Detecting existing process
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.liteengine.launcher/crc6466e7b0324888366f.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.liteengine.launcher/crc6466e7b0324888366f.MainActivity }
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/AndroidLauncher.dll
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Collections.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Threading.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Runtime.InteropServices.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/Silk.NET.Windowing.Sdl.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Memory.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/Silk.NET.Windowing.Common.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/netstandard.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Reflection.Primitives.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Runtime.CompilerServices.Unsafe.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/Silk.NET.Core.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/Silk.NET.OpenGL.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Runtime.InteropServices.RuntimeInformation.dll [External]
Loaded assembly: /data/user/0/com.liteengine.launcher/files/.__override__/System.Collections.Concurrent.dll [External]
[libc] SetHeapTaggingLevel: tag level set to 0
[engine.launche] Late-enabling -Xcheck:jni
[engine.launche] Unknown bits set in runtime_flags: 0x40000000
[ProcessState] Binder ioctl to enable oneway spam detection failed: Invalid argument
[OneTrace] Mark active for pid=9269? true
[cutils-dev] otrace_set_tracing_enabled? true
[cutils-dev] properties changed in otrace_seq_number_changed!
[CompatibilityChangeReporter] Compat change id reported: 171979766; UID 10490; state: DISABLED
[oplus.android.OplusFrameworkFactoryImpl] get feature:IOplusAutoResolutionFeature
[oplus.android.OplusFrameworkFactoryImpl] getOplusAutoResolutionFeature
[ApplicationLoaders] Returning zygote-cached class loader: /system/framework/android.test.base.jar
[Quality] LaunchTime2.0: com.liteengine.launcher createOrUpdateClassLoaderLocked took time: 10
[GraphicsEnvironment] ANGLE Developer option for 'com.liteengine.launcher' set to: 'default'
[GraphicsEnvironment] App is not on the allowlist for updatable production driver.
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~WjfIkWVF0nQ6ZnUTOOlOvg==/com.liteengine.launcher-rlQvpA7kUp2hpuOSISc4Lw==/lib/arm64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~WjfIkWVF0nQ6ZnUTOOlOvg==/com.liteengine.launcher-rlQvpA7kUp2hpuOSISc4Lw==/lib/arm64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~WjfIkWVF0nQ6ZnUTOOlOvg==/com.liteengine.launcher-rlQvpA7kUp2hpuOSISc4Lw==/lib/arm64
[debug-app-helper] Using runtime path: /data/app/~~WjfIkWVF0nQ6ZnUTOOlOvg==/com.liteengine.launcher-rlQvpA7kUp2hpuOSISc4Lw==/lib/arm64
[debug-app-helper] checking directory: `/data/user/0/com.liteengine.launcher/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.liteengine.launcher/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.liteengine.launcher/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~WjfIkWVF0nQ6ZnUTOOlOvg==/com.liteengine.launcher-rlQvpA7kUp2hpuOSISc4Lw==/lib/arm64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~WjfIkWVF0nQ6ZnUTOOlOvg==/com.liteengine.launcher-rlQvpA7kUp2hpuOSISc4Lw==/lib/arm64/libmonosgen-2.0.so
[engine.launche] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[monodroid] Creating public update directory: `/data/user/0/com.liteengine.launcher/files/.__override__`
[engine.launche] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8806,server=y,embedding=1
[monodroid-assembly] open_from_bundles: failed to load assembly AndroidLauncher.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
[engine.launche] Attempt to remove non-JNI local reference, dumping thread
[Quality] BindApplication: com.liteengine.launcher
[monodroid-assembly] open_from_bundles: failed to load assembly Silk.NET.Windowing.Sdl.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Silk.NET.Windowing.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.CompilerServices.Unsafe.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Silk.NET.Core.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Silk.NET.OpenGL.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.RuntimeInformation.dll
[SDL] Device: OnePlus8Pro
[SDL] Model: IN2020
[SDL] onCreate()
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
[SDL] nativeSetupJNI()
[SDL] AUDIO nativeSetupJNI()
[SDL] CONTROLLER nativeSetupJNI()
[hidapi] Initializing Bluetooth
[hidapi] Couldn't initialize Bluetooth, missing android.permission.BLUETOOTH
[oplus.android.OplusFrameworkFactoryImpl] Unknow feature:IOplusTextViewRTLUtilForUG
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[Parcel] Reading a NULL string not supported here.
[ScrollOptimizationHelper] can't find the config file for optimizaiton
[ScrollOptimizationHelper] will not debug for debug is false
[oplus.android.OplusFrameworkFactoryImpl] get feature:IOplusDynamicVsyncFeature
[oplus.android.OplusFrameworkFactoryImpl] get feature:IOplusDynamicVsyncFeature
[oplus.android.OplusFrameworkFactoryImpl] get feature:IOplusDynamicVsyncFeature
[OplusFeatureCache] Milliseconds spent on init(): 11
[OplusUXIconLoader] theme=2; uxIconConfig = 216702050951589906
[OplusUXIconLoader] themeCustomPos=3;commonStylePathArray size=3
[UXIconPaser] theme=2; pathData =M46.1499336,-1.86451255e-15 L103.850066,1.86451255e-15 C119.897404,-1.08333549e-15 125.716556,1.670861 131.583223,4.80838867 C137.449889,7.94591634 142.054084,12.5501107 145.191611,18.4167773 C148.329139,24.283444 150,30.1025963 150,46.1499336 L150,103.850066 C150,119.897404 148.329139,125.716556 145.191611,131.583223 C142.054084,137.449889 137.449889,142.054084 131.583223,145.191611 C125.716556,148.329139 119.897404,150 103.850066,150 L46.1499336,150 C30.1025963,150 24.283444,148.329139 18.4167773,145.191611 C12.5501107,142.054084 7.94591634,137.449889 4.80838867,131.583223 C1.670861,125.716556 7.22223659e-16,119.897404 -1.24300837e-15,103.850066 L1.24300837e-15,46.1499336 C-7.22223659e-16,30.1025963 1.670861,24.283444 4.80838867,18.4167773 C7.94591634,12.5501107 12.5501107,7.94591634 18.4167773,4.80838867 C24.283444,1.670861 30.1025963,1.08333549e-15 46.1499336,-1.86451255e-15 Z
[OplusUXIconLoader] path = android.graphics.Path@7ddd928; config = OplusIconConfig = [ isForeign : false,theme : 2,iconSize : 4375,iconShape : 0,foregroundSize : 5600,artPlusOn : true,shapePath ：null, nightMode : false;enableDarkModeIcon = true, userId = -1 ]
[OplusUXIconLoader] checkConfig sIconConfig =:OplusIconConfig = [ isForeign : false,theme : 2,iconSize : 4375,iconShape : 0,foregroundSize : 5600,artPlusOn : true,shapePath ：android.graphics.Path@e8fd641, nightMode : false;enableDarkModeIcon = true, userId = 0 ]
[SDL] onStart()
[OplusCustomizeRestrictionManager] sInstance is null, start a new sInstance
[SDL] onResume()
[OplusInputMethodUtil] init DEBUG to false, update DEBUG_IME to false
[OplusInputMethodUtil] init DEBUG to false, update DEBUG_IME to false
[OplusSlideAnimOptHelper] com.liteengine.launcher scrollEffectOpt enable = false
[WindowManager] Add to mViews: DecorView@253f735[MainActivity],pkg= com.liteengine.launcher
[SDL] onPause()
[SDL] onStop()
[SystemSensorManagerExtImpl] unRegisterListener by org.libsdl.app.SDLSurface and its name is lsm6dsm Accelerometer Non-wakeup
[SDL] onDestroy()
[SDL] SDLActivity thread ends
[SDL] Device: OnePlus8Pro
[SDL] Model: IN2020
[SDL] onCreate()
[monodroid-assembly] open_from_bundles: failed to load assembly zh-CN/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly zh-CN/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly zh-Hans/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly zh-Hans/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly zh/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly zh/System.Private.CoreLib.resources.dll
**System.InvalidOperationException:** 'Only one SilkActivity may be present throughout the whole application.'

[libc] Requested dump for tid 9269 (SDLActivity)
**System.InvalidOperationException:** 'Only one SilkActivity may be present throughout the whole application.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Only one SilkActivity may be present throughout the whole application.
[mono-rt]    at Silk.NET.Windowing.Sdl.Android.SilkActivity.LoadLibraries()
[mono-rt]    at Org.Libsdl.App.SDLActivity.n_LoadLibraries(IntPtr jnienv, IntPtr native__this)
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22

```

**Comment by Perksey** [comment]
Aha! That's actually really helpful, thanks. I'll get the bug fixed for the April update.

**Comment by CeSun** [comment]
> Aha! That's actually really helpful, thanks. I'll get the bug fixed for the April update.

Thank you very much!
😀
